#define GRASS_VERSION_STRING   "7.8.3"
#define GRASS_VERSION_MAJOR    7
#define GRASS_VERSION_MINOR    8
#define GRASS_VERSION_RELEASE  3
#define GRASS_HEADERS_VERSION  7
#define GRASS_HEADERS_DATE     7
